ktor:
  deployment:
    host: "0.0.0.0"
    port: 8080
    jwtAudience: "jwt-audience"
    jwtDomain: "your-domain.com"
    jwtRealm: "ktor sample app"
    jwtSecret: "secret-uwu"
#  application:
#    modules:
#      com.example.ApplicationKt.main